format = """
[](#9A348E)\
$os\
$username\
$sudo\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_branch\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
$zig\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#86BBD8 bg:#33658A)\
$time\
[ ](fg:#33658A)\
"""

right_format = """
$cmd_duration\
$status\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like   or disable this
# and use the os module below
[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'
disabled = false

[status]
symbol = ""
not_executable_symbol = "󰮘"
not_found_symbol = "?"
sigint_symbol = "󰗼"
signal_symbol = "󱐋"
format = '[$symbol ]($style)'
map_symbol = true
disabled = false

[cmd_duration]
style = "#2b3054"
format = '[$duration ]($style)'

[sudo]
symbol = ' '
format = '[$symbol]($style)'
style = "bg:#9a348e"
disabled = false

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E"
disabled = false # Disabled by default

[os.symbols]
Macos = " "
Debian = " "

[directory]
style = "bg:#DA627D"
read_only = " "
format = "[ $read_only$path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[zig]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[swift]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[c]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[elixir]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#FCA17D"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[gradle]
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "󰆥 "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#86BBD8"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%I:%M %P"
style = "bg:#33658A"
format = '[ ♥ $time ]($style)'
use_12hr = true
