format = """
[╭─](fg:surface0)\

$directory\

$zig\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\

$git_branch\

$git_status\

$fill\

$cmd_duration\
$status\
$sudo\

$line_break\
[│](fg:surface0)\

$line_break\
[╰─](fg:surface0)\
[♥ ](fg:pink)
"""

right_format = """

"""

palette = "catppuccin_mocha"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
# base = "#1e1e2e"
base = "#28283e"
mantle = "#181825"
crust = "#11111b"

[character]
success_symbol = "[](bold pink)"
error_symbol = "[](bold red)"

[fill]
symbol = " "

[status]
symbol = ""
not_executable_symbol = "󰮘"
not_found_symbol = "?"
sigint_symbol = "󰗼"
signal_symbol = "󱐋"
style = "bg:base fg:red"
format = '[](fg:base bg:none)[$symbol]($style)[](fg:base bg:none) '
map_symbol = true
disabled = false

[cmd_duration]
style = "bg:base fg:subtext1"
format = '[](fg:base bg:none)[$duration]($style)[](fg:base bg:none) '

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:base"
disabled = false # Disabled by default

[os.symbols]
Macos = ""
Debian = ""
NixOS = "󱄅"

[sudo]
symbol = ''
format = '[](fg:base bg:none)[$symbol]($style)[](fg:base bg:none)'
style = "bg:base fg:red"
disabled = false

[directory] # 
format = "[](fg:base bg:none)[$path$read_only](fg:mauve bg:base)[](fg:base bg:none) "
read_only = "  "
truncation_length = 4
truncate_to_repo = false
truncation_symbol = "…/"
use_os_path_sep = true

[git_branch]
style = "bg:base fg:maroon"
format = '[](fg:base bg:none)[$branch]($style)[](fg:base bg:none) '

[git_status] #    
format = "[](fg:base bg:none)$ahead_behind[](fg:base bg:none) $stashed$staged$modified$renamed$deleted$untracked"

up_to_date = "[](fg:green bg:base)"
ahead = "[ahead\\(×${count}\\)](fg:yellow bg:base)"
behind = "[behind\\(×${count}\\)](fg:yellow bg:base)"
conflicted = "[ conflicted ](fg:red bg:base)"
diverged = "[ diverged ](fg:red bg:base)$ahead_behind"

#   → ✗ 
staged = "[](fg:base bg:none)[${count}!](fg:green bg:base)[](fg:base bg:none) "
modified = "[](fg:base bg:none)[${count}!](fg:yellow bg:base)[](fg:base bg:none) "
untracked = "[](fg:base bg:none)[${count}?](fg:red bg:base)[](fg:base bg:none) "
renamed = "[](fg:base bg:none)[${count}→](fg:green bg:base)[](fg:base bg:none) "
deleted = "[](fg:base bg:none)[${count}✗](fg:red bg:base)[](fg:base bg:none) "
stashed = "[](fg:base bg:none)[${count}\\$](fg:blue bg:base)[](fg:base bg:none) "

[zig]
symbol = ""
style = "bg:base fg:yellow"
format = '[](fg:base)[$symbol ($version)]($style)[ ](fg:base)'

[swift]
symbol = ""
style = "bg:blue"
format = '[](fg:base)[$symbol ($version)]($style)[ ](fg:base)'

[c]
symbol = ""
style = "bg:blue"
format = '[](fg:base)[$symbol ($version)]($style)[ ](fg:base)'

[elixir]
symbol = ""
style = "bg:blue"
format = '[](fg:base)[$symbol ($version)]($style)[ ](fg:base)'

[elm]
symbol = ""
style = "bg:blue"
format = '[](fg:base)[$symbol ($version)]($style)[ ](fg:base)'

[golang]
symbol = ""
style = "bg:blue"
format = '[](fg:base)[$symbol ($version)]($style)[ ](fg:base)'

[gradle]
style = "bg:blue"
format = '[](fg:base)[$symbol ($version)]($style)[ ](fg:base)'

[haskell]
symbol = ""
style = "bg:blue"
format = '[](fg:base)[$symbol ($version)]($style)[ ](fg:base)'

[java]
symbol = ""
style = "bg:blue"
format = '[](fg:base)[$symbol ($version)]($style)[ ](fg:base)'

[julia]
symbol = ""
style = "bg:blue"
format = '[](fg:base)[$symbol ($version)]($style)[ ](fg:base)'

[nodejs]
symbol = ""
style = "bg:blue"
format = '[](fg:base)[$symbol ($version)]($style)[ ](fg:base)'

[nim]
symbol = "󰆥"
style = "bg:blue"
format = '[](fg:base)[$symbol ($version)]($style)[ ](fg:base)'

[rust]
symbol = ""
style = "bg:base fg:peach"
format = '[](fg:base)[$symbol ($version)]($style)[ ](fg:base)'

[scala]
symbol = ""
style = "bg:blue"
format = '[](fg:base)[$symbol ($version)]($style)[ ](fg:base)'
